import { NextResponse } from 'next/server';
import type { EmailOtpType } from '@supabase/supabase-js';
import { createClient } from '@/lib/supabase/server';
import { forwardedIdentityHeaders } from '@/lib/clientAddress';

/** Where an invite link lands, build handoff step 2.
 *
 *  WHY THIS EXISTS RATHER THAN REUSING THE RESET FLOW. /login/reset/confirm
 *  already turns a one-time link into a session and lets somebody set a
 *  password, so it looks like the obvious home for an invite. It is not, and
 *  its own header says why: it exchanges a PKCE `?code=`, and "the exchange
 *  only succeeds in the browser that asked for the email".
 *
 *  That constraint is correct for a reset, which the person requested
 *  themselves a moment earlier in that same browser. It can never hold for an
 *  invite: the link is generated by an administrator, on their machine, and
 *  sent to somebody else. There is no code verifier in the recipient's browser
 *  to match, so a PKCE invite fails for every single recipient.
 *
 *  A token_hash is verified server side instead, here, with no browser state
 *  involved at all. The session cookies are set on this response, so by the
 *  time the recipient reaches the page below they are signed in and can choose
 *  a password. One link, one click: the address is confirmed by the same
 *  verification that signs them in, which is the "in one step" the handoff asks
 *  for.
 *
 *  SINGLE USE, and failure is deliberately quiet about which failure it was. An
 *  expired link, an already-used link and a forged token all redirect to the
 *  same place with the same message. Telling an anonymous caller which of the
 *  three they hit turns this route into an oracle for guessing token hashes. */
export async function GET(request: Request): Promise<NextResponse> {
  const url = new URL(request.url);
  const tokenHash = url.searchParams.get('token_hash');
  const type = url.searchParams.get('type') as EmailOtpType | null;

  /* `next` is a path this route redirects to, so it is an open-redirect risk if
     taken at face value. Only a same-origin absolute path is honoured, and
     anything else falls back to the invite page rather than being rejected
     loudly: a recipient with a slightly mangled link should still land
     somewhere that works. `//host` is excluded explicitly because it is a
     protocol-relative URL, which `startsWith('/')` alone would let through. */
  const requested = url.searchParams.get('next') ?? '';
  const next =
    requested.startsWith('/') && !requested.startsWith('//') ? requested : '/login/reset/confirm?invite=1';

  if (!tokenHash || !type) {
    return NextResponse.redirect(new URL('/login?e=invite-link', url.origin));
  }

  /* The visitor's own address and browser, for the same reason /auth/sign-in
     forwards them: this route creates a session server-side too, so without
     this auth.sessions records the Vercel function rather than the person.
     This is the half that was missed first time round — every invite
     acceptance, password reset and magic-link sign-in comes through here, and
     an invite acceptance is the FIRST session a new club's account ever has. */
  const supabase = await createClient(forwardedIdentityHeaders(request.headers));
  const { error } = await supabase.auth.verifyOtp({ type, token_hash: tokenHash });

  if (error) {
    return NextResponse.redirect(new URL('/login?e=invite-link', url.origin));
  }

  return NextResponse.redirect(new URL(next, url.origin));
}
