/* THE SPACE BETWEEN TWO ATHLETE BODY BLOCKS MUST COME FROM ONE PLACE.
 *
 * WHY THIS EXISTS. `.phone-body` is `display: flex; flex-direction: column;
 * gap: var(--gap-stack)`, so the shell already supplies the space between body
 * blocks. Flex children do not collapse margins, so a child that ALSO sets a
 * vertical margin adds to the gap: 14 + 14 = 28. Measured on production, eight
 * of the ten athlete screens render their body gaps between 18px and 40.5px
 * where base.css's own comment says 14px, and only Today and Programme are
 * clean -- because they are the only two screens where no child sets a margin.
 * Filed as 0h in the architecture to-do list.
 *
 * THE VALUE LIVES IN --gap-body (28px since 2026-09-08). WHAT THIS DOES NOT DO:
 * enforce a NUMBER. Whether 14px or 28px is correct is an
 * open decision (0h states both readings), and a guard that picked a side would
 * be pre-empting it. This pins the SET of offenders instead, so the problem
 * cannot grow while the decision is pending, and so the fix -- whenever it
 * lands -- announces itself here.
 *
 * IT FAILS IN BOTH DIRECTIONS, deliberately. A new offender is a regression. A
 * REMOVED offender is the fix landing, and the baseline should shrink to match;
 * a guard that silently accepts improvement stops describing the code.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { topLevelChildren, cls, inlineMargin } from './lib/phone-body-children.mjs';

/* The 25 phone-body children that carry their own vertical margin today.
 * Generated by this script, reviewed by hand, and pinned. Sorted so a diff is
 * readable. */
/* FIXED 2026-09-08: Isabella chose 14px, and 24 of the original 25 offenders
 * are gone. What did it:
 *   - `.phone-body > * { margin-block: 0 }` in base.css states the invariant
 *     once, and neutralises the CSS-class offenders WITHOUT touching those
 *     classes where they are used elsewhere (.nutr-meal-grid is also a staff
 *     component's child, where its 18px is real).
 *   - the 16 inline vertical margins were removed from the pages, because an
 *     inline style beats any rule and the reset could not reach them.
 *   - three now-dead declarations were deleted outright: .me-stats,
 *     .md-seg-track and .sheet-head.
 *
 * ONE ENTRY REMAINS, and it is correct rather than pending. `.nutr-meal-grid`
 * still declares margin-top: 18px because NutritionWorkspace needs it; on the
 * athlete screen the reset neutralises it. It is pinned so that removing the
 * reset rule, or moving that class, shows up here. */
const BASELINE: readonly string[] = [
  /* .nutr-meal-grid's margin-top: 18px is DECLARED but neutralised on the
   * athlete screen by the reset rule, and is real inside NutritionWorkspace on
   * a staff screen where the class is not a phone-body child. Pinned so that
   * removing the reset, or moving that class, shows up here. */
  '/programme/nutrition/page.tsx <div> .nutr-meal-grid margin-top: 18px',
];

/* COMMENTS STRIPPED BEFORE ANYTHING IS MATCHED. Found the hard way: the note
 * above .me-stats quotes the reset rule verbatim -- ".phone-body > * {
 * margin-block: 0 }" -- so the premise check below matched the DOCUMENTATION
 * and reported the rule present after it had been deleted. A file that
 * discusses a rule is not a file that applies one. */
const css = readFileSync('src/styles/base.css', 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');

function cssMargin(klass: string): string | null {
  const esc = klass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = new RegExp(`(^|[,}])\\s*\\.${esc}\\s*\\{([^}]*)\\}`, 'm').exec(css);
  if (!m) return null;
  const v = /(margin-top|margin-bottom)\s*:\s*([^;]+);/.exec(m[2] ?? '');
  return v ? `${v[1]}: ${(v[2] ?? '').trim()}` : null;
}

const pages: string[] = [];
(function walk(d: string) {
  for (const e of readdirSync(d)) {
    const p = join(d, e);
    if (statSync(p).isDirectory()) walk(p);
    else if (e === 'page.tsx') pages.push(p);
  }
})('src/app/(athlete)');

const found: string[] = [];
for (const p of pages.sort()) {
  for (const k of topLevelChildren(readFileSync(p, 'utf8'))) {
    const where = `${p.replace('src/app/(athlete)', '')} <${k.tag}${k.via ? ` via ${k.via}` : ''}>`;
    const inline = inlineMargin(k.attrs);
    if (inline) found.push(`${where} inline ${inline}`);
    const classes = cls(k.attrs).split(/\s+/).filter(Boolean);
    for (const c of classes) {
      const v = cssMargin(c);
      if (v) { found.push(`${where} .${c} ${v}`); break; }
    }
  }
}
found.sort();

/* The premise. If the shell stops supplying the gap, everything above is moot
   and the guard should say so rather than keep passing. */
const shell = /\.phone-body\s*\{([^}]*)\}/.exec(css)?.[1] ?? '';
const shellOk = /gap:\s*var\(--gap-body\)/.test(shell) && /display:\s*flex/.test(shell);
/* THE RESET IS LOAD-BEARING NOW. It is what keeps a CSS-class margin on a
   phone-body child harmless — including .nutr-meal-grid's, the one entry left
   in the baseline. Without it that class silently re-breaks the athlete screen
   while the staff screen still needs the declaration. */
const reset = /\.phone-body\.phone-body\s*>\s*\*\s*\{([^}]*)\}/.exec(css)?.[1] ?? '';
/* PHYSICAL LONGHANDS, matching what the rule actually declares. This assertion
   said `margin-block: 0` for one revision, after the rule had been changed to
   margin-top/margin-bottom — because `margin-block: 0` did not in fact beat
   .nutr-meal-grid's `margin-top: 18px`. The guard failed the build on its own
   stale expectation, which is the correct behaviour and how it was noticed. */
const resetOk = /margin-top:\s*0/.test(reset) && /margin-bottom:\s*0/.test(reset);

const base = [...BASELINE].sort();
const added = found.filter((f) => !base.includes(f));
const removed = base.filter((b) => !found.includes(b));

if (!shellOk) {
  console.error('\n.phone-body no longer supplies the gap this guard is about.');
  console.error('Its rule must keep `display: flex` and `gap: var(--gap-body)`, or 0h needs rewriting.\n');
  process.exit(1);
}
if (!resetOk) {
  console.error('\n`.phone-body.phone-body > *` no longer zeroes margin-top and margin-bottom.');
  console.error('(the class is doubled deliberately — it needs (0,2,0) to beat .nutr-meal-grid,');
  console.error(' and the longhands are deliberate too: margin-block did not beat margin-top)');
  console.error(`
That rule is what makes a class margin on a phone-body child harmless. Without
it, .nutr-meal-grid's 18px (which a staff screen genuinely needs) starts adding
to the athlete shell's gap again, and so does anything else added later. Restore
it, or remove the class margins it was covering. See 0h.
`);
  process.exit(1);
}

if (added.length === 0 && removed.length === 0) {
  console.log(`Athlete spacing: ${found.length} phone-body children carry their own vertical margin, matching the pinned set.`);
  process.exit(0);
}

if (added.length) {
  console.error(`\nAthlete spacing: ${added.length} NEW phone-body child(ren) set their own vertical margin.\n`);
  for (const a of added) console.error(`  + ${a}`);
  console.error(`
.phone-body is a flex column with gap: var(--gap-stack). A child that also sets
margin-top ADDS to that gap, so this block will render at roughly double the
intended distance from its neighbour. Take the margin off and let the gap do the
work. See 0h in docs/Fydr_-_Architecture_To-Do_List.md.
`);
}
if (removed.length) {
  console.error(`\nAthlete spacing: ${removed.length} pinned offender(s) are gone -- good, but the baseline is now stale.\n`);
  for (const r of removed) console.error(`  - ${r}`);
  console.error(`
Remove those lines from BASELINE in scripts/check-athlete-spacing.ts. This guard
fails on improvement on purpose: a baseline that quietly absorbs fixes stops
describing the code.
`);
}
process.exit(1);
