/* THE SPACE BETWEEN TWO ATHLETE BODY BLOCKS MUST COME FROM ONE PLACE.
 *
 * WHY THIS EXISTS. `.phone-body` is `display: flex; flex-direction: column;
 * gap: var(--gap-stack)`, so the shell already supplies the space between body
 * blocks. Flex children do not collapse margins, so a child that ALSO sets a
 * vertical margin adds to the gap: 14 + 14 = 28. Measured on production, eight
 * of the ten athlete screens render their body gaps between 18px and 40.5px
 * where base.css's own comment says 14px, and only Today and Programme are
 * clean -- because they are the only two screens where no child sets a margin.
 * Filed as 0h in the architecture to-do list.
 *
 * WHAT IT DOES NOT DO: enforce a NUMBER. Whether 14px or 28px is correct is an
 * open decision (0h states both readings), and a guard that picked a side would
 * be pre-empting it. This pins the SET of offenders instead, so the problem
 * cannot grow while the decision is pending, and so the fix -- whenever it
 * lands -- announces itself here.
 *
 * IT FAILS IN BOTH DIRECTIONS, deliberately. A new offender is a regression. A
 * REMOVED offender is the fix landing, and the baseline should shrink to match;
 * a guard that silently accepts improvement stops describing the code.
 */
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { topLevelChildren, cls, inlineMargin } from './lib/phone-body-children.mjs';

/* The 25 phone-body children that carry their own vertical margin today.
 * Generated by this script, reviewed by hand, and pinned. Sorted so a diff is
 * readable. */
const BASELINE: readonly string[] = [
  '/check-in/page.tsx <div> .sheet-head margin-bottom: 12px',
  '/me/leaderboards/page.tsx <div> .sheet-head margin-bottom: 12px',
  '/me/leaderboards/page.tsx <section> inline marginTop: 14',
  '/me/leaderboards/page.tsx <section> inline marginTop: 14',
  '/me/page.tsx <div> .me-stats margin-top: 14px',
  '/me/page.tsx <div> inline marginTop: 14',
  '/me/page.tsx <div> inline marginTop: 14',
  '/my-data/boards/[leaderboardId]/page.tsx <div> .sheet-head margin-bottom: 12px',
  '/my-data/gym/[gymSessionLogId]/page.tsx <div> inline marginTop: 14',
  '/my-data/gym/[gymSessionLogId]/page.tsx <p> inline marginTop: 14',
  '/my-data/page.tsx <div via GymTab> inline marginTop: 14',
  '/my-data/page.tsx <div via NutritionTab> inline marginTop: 14',
  '/my-data/page.tsx <div via TestingTab> inline marginTop: 14',
  '/my-data/page.tsx <div via TrainingTab> inline marginTop: 14',
  '/my-data/page.tsx <div via WellnessTab> inline marginTop: 14',
  '/my-data/page.tsx <div> .md-seg-track margin-top: 4px',
  '/my-data/page.tsx <div> inline marginTop: 12',
  '/my-data/page.tsx <div> inline marginTop: 14',
  '/nutrition-check-in/page.tsx <div> .sheet-head margin-bottom: 12px',
  '/programme/nutrition/page.tsx <div> .nutr-meal-grid margin-top: 18px',
  '/programme/nutrition/page.tsx <p> inline marginBottom: 4',
  '/programme/nutrition/page.tsx <p> inline marginTop: 14',
  '/report-problem/page.tsx <div> .sheet-head margin-bottom: 12px',
  '/report-problem/page.tsx <section> inline marginTop: 20',
  '/rpe/[sessionId]/page.tsx <div> .sheet-head margin-bottom: 12px',
];

const css = readFileSync('src/styles/base.css', 'utf8');

function cssMargin(klass: string): string | null {
  const esc = klass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const m = new RegExp(`(^|[,}])\\s*\\.${esc}\\s*\\{([^}]*)\\}`, 'm').exec(css);
  if (!m) return null;
  const v = /(margin-top|margin-bottom)\s*:\s*([^;]+);/.exec(m[2] ?? '');
  return v ? `${v[1]}: ${(v[2] ?? '').trim()}` : null;
}

const pages: string[] = [];
(function walk(d: string) {
  for (const e of readdirSync(d)) {
    const p = join(d, e);
    if (statSync(p).isDirectory()) walk(p);
    else if (e === 'page.tsx') pages.push(p);
  }
})('src/app/(athlete)');

const found: string[] = [];
for (const p of pages.sort()) {
  for (const k of topLevelChildren(readFileSync(p, 'utf8'))) {
    const where = `${p.replace('src/app/(athlete)', '')} <${k.tag}${k.via ? ` via ${k.via}` : ''}>`;
    const inline = inlineMargin(k.attrs);
    if (inline) found.push(`${where} inline ${inline}`);
    const classes = cls(k.attrs).split(/\s+/).filter(Boolean);
    for (const c of classes) {
      const v = cssMargin(c);
      if (v) { found.push(`${where} .${c} ${v}`); break; }
    }
  }
}
found.sort();

/* The premise. If the shell stops supplying the gap, everything above is moot
   and the guard should say so rather than keep passing. */
const shell = /\.phone-body\s*\{([^}]*)\}/.exec(css)?.[1] ?? '';
const shellOk = /gap:\s*var\(--gap-stack\)/.test(shell) && /display:\s*flex/.test(shell);

const base = [...BASELINE].sort();
const added = found.filter((f) => !base.includes(f));
const removed = base.filter((b) => !found.includes(b));

if (!shellOk) {
  console.error('\n.phone-body no longer supplies the gap this guard is about.');
  console.error('Its rule must keep `display: flex` and `gap: var(--gap-stack)`, or 0h needs rewriting.\n');
  process.exit(1);
}

if (added.length === 0 && removed.length === 0) {
  console.log(`Athlete spacing: ${found.length} phone-body children carry their own vertical margin, matching the pinned set.`);
  process.exit(0);
}

if (added.length) {
  console.error(`\nAthlete spacing: ${added.length} NEW phone-body child(ren) set their own vertical margin.\n`);
  for (const a of added) console.error(`  + ${a}`);
  console.error(`
.phone-body is a flex column with gap: var(--gap-stack). A child that also sets
margin-top ADDS to that gap, so this block will render at roughly double the
intended distance from its neighbour. Take the margin off and let the gap do the
work. See 0h in docs/Fydr_-_Architecture_To-Do_List.md.
`);
}
if (removed.length) {
  console.error(`\nAthlete spacing: ${removed.length} pinned offender(s) are gone -- good, but the baseline is now stale.\n`);
  for (const r of removed) console.error(`  - ${r}`);
  console.error(`
Remove those lines from BASELINE in scripts/check-athlete-spacing.ts. This guard
fails on improvement on purpose: a baseline that quietly absorbs fixes stops
describing the code.
`);
}
process.exit(1);
