/* PATTERN-S7 C1 (reconciled 2026-09-13): the report catalogue and the shell's
 * definition slot. docs/reports-catalogue-source.md is Isabella's and is not
 * edited; docs/reports-catalogue.md is the working copy reconciled against it;
 * src/lib/reportCatalogue.ts mirrors the working copy's sentences verbatim.
 * The source's confirmed sentences must appear in the working copy word for
 * word; the reports that carry a sentence carry it on screen, in print and in
 * both exports; the two with none (training — raised; match — on hold) carry
 * none anywhere. */
import { readFileSync } from 'node:fs';
import { REPORT_DEFINITIONS, athleteDefinition, reportDefinition } from '@/lib/reportCatalogue';

let failed = 0;
function assert(cond: boolean, msg: string) {
  if (cond) console.log(`  ok - ${msg}`);
  else { failed++; console.log(`  FAIL - ${msg}`); }
}
const read = (p: string) => readFileSync(p, 'utf8');
const strip = (s: string) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

console.log('1. the source, the working copy and the module agree');
{
  const source = read('docs/reports-catalogue-source.md');
  const work = read('docs/reports-catalogue.md');
  const sourceSentence = (heading: string) => {
    const sec = source.slice(source.indexOf(`## ${heading}`));
    return sec.match(/\*\*Definition sentence \(draft\):\*\* "([^"]+)"/)?.[1] ?? null;
  };
  const workSentence = (heading: string) => {
    const sec = work.slice(work.indexOf(`## ${heading}`));
    return sec.match(/\*\*Definition sentence[^:]*:\*\* "([^"]+)"/)?.[1] ?? null;
  };
  for (const [src, wrk, key] of [
    ['1. Training report', '1. Training report', 'training'],
    ['3. Squad weekly report', '3. Squad weekly report', 'squad'],
    ['4. Athlete report', '4. Athlete report', 'athlete'],
    ['5. Testing report', '5. Testing report', 'testing'],
  ] as const) {
    const s = sourceSentence(src);
    const w = workSentence(wrk);
    assert(s !== null && s === w, `${key}: the working copy carries the source's confirmed sentence verbatim`);
    if (key !== 'training') assert(REPORT_DEFINITIONS[key] === s, `${key}: the module mirrors it`);
  }
  assert(REPORT_DEFINITIONS.training === null && /raised on the sheet/i.test(work.slice(work.indexOf('## 1. Training'), work.indexOf('## 2. Match'))), 'training: the confirmed sentence is not put on the GPS board — null in the module, raised in the working copy');
  assert(/ON HOLD/.test(work.slice(work.indexOf('## 2. Match'), work.indexOf('## 3. Squad'))) && !('match' in REPORT_DEFINITIONS), 'match: on hold, no sentence anywhere');
  assert(/does \*\*not\*\* record who played or minutes/.test(work), 'match: the open question is answered in the working copy');
  for (const key of ['compliance', 'injuries'] as const) {
    const heading = key === 'compliance' ? '6. Compliance' : '7. Injury and availability';
    const w = workSentence(heading);
    assert(w !== null && REPORT_DEFINITIONS[key] === w && /drafted by the builder, pending/.test(work.slice(work.indexOf(`## ${heading}`), work.indexOf(`## ${heading}`) + 400)), `${key}: the builder's draft, marked pending, mirrored by the module`);
  }
  assert(athleteDefinition({ athlete: 'Dan Okonkwo', start: 'Mon 17 Aug', end: 'Sun 13 Sept' }) === 'Everything recorded for Dan Okonkwo between Mon 17 Aug and Sun 13 Sept. Sections with no data say so rather than showing zeros.', 'the athlete sentence resolves its three placeholders');
  assert(reportDefinition('squad') === REPORT_DEFINITIONS.squad, 'reportDefinition reads the map');
  assert(!/Do not edit this file/.test(work) && /SOURCE OF TRUTH/.test(source), 'the source is the source; the working copy does not claim to be');
}

console.log('\n2. the shell carries the definition');
{
  const header = strip(read('src/components/ReportHeader/ReportHeader.tsx'));
  assert(/definition\?: string;/.test(header) && /\{definition \? \(\s*<div className="card rhead-definition">\s*<p>\{definition\}<\/p>\s*<\/div>\s*\) : null\}/.test(header), 'ReportHeader renders the sentence as a --surf card above the numbers, nothing for none');
  const css = strip(read('src/styles/base.css'));
  assert(/\.rhead-definition\s*\{[^}]*max-width:\s*100ch;[^}]*\}/.test(css), 'capped at 100ch');
  const pdf = strip(read('src/lib/pdf.tsx'));
  assert(/definition\?: string;/.test(pdf) && /\{definition \? <Text style=\{pdfStyles\.definition\}>\{definition\}<\/Text> : null\}/.test(pdf), 'PdfHeader renders it under the title, nothing for none');
}

console.log('\n3. the reports that carry a sentence carry it everywhere; the two without carry it nowhere');
{
  const withSentence: { key: 'compliance' | 'injuries' | 'squad' | 'testing'; dir: string; spec: string; viaPager: boolean }[] = [
    { key: 'compliance', dir: 'compliance', spec: 'docs/screens/20-compliance-report.md', viaPager: true },
    { key: 'injuries', dir: 'injuries', spec: 'docs/screens/24-injury-report.md', viaPager: true },
    { key: 'squad', dir: 'squad', spec: 'docs/screens/21-squad-weekly-report.md', viaPager: false },
    { key: 'testing', dir: 'testing', spec: 'docs/screens/22-testing-report.md', viaPager: true },
  ];
  for (const r of withSentence) {
    const page = strip(read(`src/app/(staff)/reports/${r.dir}/page.tsx`));
    assert(new RegExp(r.viaPager ? `definition: reportDefinition\\('${r.key}'\\) \\?\\? undefined,` : `definition=\\{reportDefinition\\('${r.key}'\\) \\?\\? undefined\\}`).test(page), `${r.key}: on screen`);
    const csv = strip(read(`src/app/(staff)/reports/${r.dir}/export/route.ts`));
    assert(new RegExp(`\\(reportDefinition\\('${r.key}'\\) \\? \`# \\$\\{reportDefinition\\('${r.key}'\\)\\}\\\\r\\\\n\` : ''\\) \\+`).test(csv), `${r.key}: first line of the CSV`);
    const pdf = strip(read(`src/app/(staff)/reports/${r.dir}/pdf/route.tsx`));
    assert(new RegExp(`definition=\\{reportDefinition\\('${r.key}'\\) \\?\\? undefined\\}`).test(pdf), `${r.key}: under the PDF's title`);
    assert(/definition sentence/i.test(read(r.spec)), `${r.key}: the spec says so`);
  }
  const athletePage = strip(read('src/app/(staff)/reports/athlete/[athleteId]/page.tsx'));
  assert(/<p>\{athleteDefinition\(\{ athlete: `\$\{athlete\.first_name\} \$\{athlete\.last_name\}`, start: formatDate\(report\.from, timezone\), end: formatDate\(report\.to, timezone\) \}\)\}<\/p>/.test(athletePage), 'athlete: the resolved sentence on screen');
  assert(/athleteDefinition\(\{ athlete: `\$\{athlete\.first_name\} \$\{athlete\.last_name\}`, start: report\.from, end: report\.to \}\)/.test(strip(read('src/app/(staff)/reports/athlete/[athleteId]/export/route.ts'))), 'athlete: in the CSV');
  assert(/definition=\{athleteDefinition\(\{/.test(strip(read('src/app/(staff)/reports/athlete/[athleteId]/pdf/route.tsx'))), 'athlete: in the PDF');
  const training = strip(read('src/app/(staff)/reports/training/page.tsx'));
  assert(/definition=\{reportDefinition\('training'\) \?\? undefined\}/.test(training), 'training: the header is handed null and draws nothing (no drafted sentence remains)');
  const trainingCsv = strip(read('src/app/(staff)/reports/training/export/route.ts'));
  assert(!/`# \$\{reportDefinition\('training'\)\}\\r\\n` \+/.test(trainingCsv) && (trainingCsv.match(/reportDefinition\('training'\) \? /g) ?? []).length === 2, 'training and match CSVs: the line only once there is a sentence');
  const trainingPdf = strip(read('src/app/(staff)/reports/training/pdf/route.tsx'));
  assert((trainingPdf.match(/definition=\{reportDefinition\('training'\) \?\? undefined\}/g) ?? []).length === 2, 'both PDFs likewise');
}

console.log(`\n${failed === 0 ? 'all passed' : `${failed} failed`}`);
if (failed > 0) process.exit(1);
