-- ---------------------------------------------------------------------------
-- ROLLBACK for migrations 0063 to 0072, the five-role model push.
--
-- NOT a migration. It lives outside supabase/migrations/ on purpose so that
-- `supabase db push` can never pick it up. Run it by hand, against an explicit
-- --db-url, and only deliberately.
--
-- GENERATED BY DIFFING, not by reading the migration files. Production was still
-- at 0062 when this was produced, so it was the authoritative "before"; scratch
-- carried all ten, so it was the "after". Every statement below restores what
-- production actually had rather than what the up-migrations claim they changed.
--
--   8 policies created by the push and dropped here
--   128 policies altered by the push and restored to production's definitions
--   11 policies the push removed and recreated here
--   10 function bodies restored from production's own pg_get_functiondef
--
-- WHAT THIS CANNOT UNDO, and it is the one thing worth reading twice.
--
-- `alter type ... add value` has no inverse: Postgres answers
-- `0A000 dropping an enum value is not implemented`, tested rather than assumed.
-- So after this script runs, app_role reads
--
--     athlete, coach, medical, admin, strength_conditioning, nutritionist
--
-- The two extra labels are inert: no row holds them, no policy names them, and
-- nothing reads them. Removing them needs a full type rebuild touching 2
-- columns, 138 policies and 11 functions, which is a far more dangerous
-- operation than the deploy it would be undoing. Leave them.
--
-- ORDER MATTERS. The enum is renamed back FIRST, because the restored policies
-- below name 'medical' and 'admin' and those labels have to exist before a
-- policy can be created against them.
--
-- WHAT THIS DOES NOT TOUCH. No migration in 0063 to 0072 rewrites a row, so
-- there is nothing to restore on the data side. Verified by stripping function
-- bodies and searching for top-level DML: none. The enum rename relabels stored
-- values, and renaming back relabels them again, which is why it is safe.
--
--   Run:  npx supabase@2.116.0 ... or psql, against --db-url, then confirm with
--         select enumlabel from pg_enum ... and npm run test:tenancy
-- ---------------------------------------------------------------------------

begin;

-- 1. The enum, back to the four values production had. Reversible, tested.
alter type app_role rename value 'medic' to 'medical';
alter type app_role rename value 'sport_scientist' to 'admin';

-- Restore the 10 function bodies 0065 replaced, exactly as production has them today.
CREATE OR REPLACE FUNCTION public.auth_roles()
 RETURNS app_role[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(
    array(
      select r::public.app_role
      from jsonb_array_elements_text(
        case
          when jsonb_typeof(public.auth_claims() #> '{app_metadata,roles}') = 'array'
            then public.auth_claims() #> '{app_metadata,roles}'
          else '[]'::jsonb
        end
      ) as t(r)
      where r in ('athlete', 'coach', 'medical', 'admin')
    ),
    '{}'::public.app_role[]
  );
$function$
;
CREATE OR REPLACE FUNCTION public.compute_leaderboard(p_leaderboard_id uuid)
 RETURNS TABLE("position" integer, athlete_id uuid, first_name text, last_name text, value numeric, record_count integer, is_tied boolean, previous_position integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  lb    leaderboards%rowtype;
  md    metric_definitions%rowtype;
  v_from date;
  v_to   date;
  v_is_staff boolean;
  v_caller_athlete uuid;
begin
  select * into lb from leaderboards
   where id = p_leaderboard_id and org_id = auth_org_id() and deleted_at is null;
  if lb.id is null then
    return;
  end if;

  select * into md from metric_definitions where key = lb.metric_key;
  if md.key is null or not md.leaderboard_eligible then
    raise exception 'metric_not_eligible' using errcode = 'P0001';
  end if;

  v_is_staff := auth_has_any_role(array['coach','medical']::app_role[]);
  v_caller_athlete := auth_athlete_id();

  -- Staff may preview a draft board. Nobody else may see a staff-only board at all.
  if not v_is_staff and lb.visibility <> 'published' then
    return;
  end if;

  v_to := coalesce(lb.window_to, current_date);
  v_from := case lb.window_type
              when 'days'     then v_to - lb.window_days
              when 'season'   then coalesce(
                                     (select starts_on from seasons
                                       where org_id = lb.org_id and is_current
                                       limit 1),
                                     v_to - 365)
              when 'all_time' then date '1900-01-01'
              else lb.window_from
            end;

  return query
  with population as (
    select a.id as athlete_id, a.first_name, a.last_name
    from athletes a
    where a.org_id = lb.org_id
      and a.deleted_at is null
      and a.status <> 'left_club'
      and (
        lb.population_type = 'squad'
        or (lb.population_type = 'selected' and a.id = any(lb.athlete_ids))
        or (lb.population_type = 'group' and exists (
              select 1 from group_memberships gm
              where gm.athlete_id = a.id and gm.group_id = lb.group_id
                and gm.removed_at is null)))
      and (not lb.exclude_unavailable or coalesce((
            select av.status from availability av
            where av.athlete_id = a.id and av.effective_to is null
            order by av.effective_from desc limit 1), 'available') = 'available')
      and not exists (
        select 1 from leaderboard_opt_outs o
        where o.athlete_id = a.id
          and (o.leaderboard_id = lb.id or o.leaderboard_id is null)
          and o.ended_at is null)
      -- Children's Code standard 7: an under-18 athlete is on a board only where they
      -- granted leaderboard_visibility themselves. Enforced here, in the query, not in
      -- a client — screens/leaderboards.md "Athletes under 18: opt-in, not opt-out".
      -- Unchanged from 0016, and now covering GPS boards for free precisely because it
      -- filters the population rather than any one metric's own branch.
      and (
        not athlete_is_minor(a.id)
        or exists (
          select 1 from athlete_consents c
          where c.athlete_id = a.id
            and c.purpose = 'leaderboard_visibility'
            and c.granted_at is not null
            and c.withdrawn_at is null)
      )
  ),
  -- The metric dispatcher. Two training branches from 0016, unchanged, plus one GPS
  -- branch covering all nine gps.* keys — see this migration's header for why the GPS
  -- metrics share a branch where the training ones cannot.
  raw as (
    select te.athlete_id, te.entry_date as record_date, te.session_load as value
    from training_entries_current te
    join population p on p.athlete_id = te.athlete_id
    where lb.metric_key = 'training.total_session_load'
      and te.entry_date between v_from and v_to
      and te.session_load is not null
    union all
    select sa.athlete_id, sa.recorded_at::date as record_date, 1::numeric as value
    from session_attendance sa
    join population p on p.athlete_id = sa.athlete_id
    where lb.metric_key = 'training.sessions_attended'
      and sa.attendance in ('full', 'modified')
      and sa.recorded_at::date between v_from and v_to
    union all
    select gv.athlete_id, gv.record_date, gv.value
    from (
      select g.athlete_id, g.record_date,
             (case lb.metric_key
                when 'gps.total_distance_m'       then g.total_distance_m
                when 'gps.running_distance_m'     then g.running_distance_m
                when 'gps.high_speed_distance_m'  then g.high_speed_distance_m
                when 'gps.sprint_distance_m'      then g.sprint_distance_m
                when 'gps.high_intensity_efforts' then g.high_intensity_efforts
                when 'gps.max_speed_ms'           then g.max_speed_ms
                when 'gps.accelerations'          then g.accelerations
                when 'gps.decelerations'          then g.decelerations
                when 'gps.player_load'            then g.player_load
              end)::numeric as value
      from gps_records g
      join population p on p.athlete_id = g.athlete_id
      where lb.metric_key like 'gps.%'
        and g.org_id = lb.org_id
        and g.record_date between v_from and v_to
    ) gv
    where gv.value is not null
  ),
  agg as (
    select
      r.athlete_id,
      count(*)::int as record_count,
      case lb.aggregation
        when 'best'   then case when md.higher_is_better
                                then max(r.value) else min(r.value) end
        when 'latest' then (array_agg(r.value order by r.record_date desc))[1]
        when 'mean'   then avg(r.value)
        when 'total'  then sum(r.value)
        when 'count'  then count(*)::numeric
      end as value
    from raw r
    group by r.athlete_id
    having count(*) >= lb.min_records
  ),
  ranked as (
    select
      p.athlete_id, p.first_name, p.last_name,
      a.value, a.record_count,
      rank() over (order by
        case when md.higher_is_better then a.value end desc nulls last,
        case when not md.higher_is_better then a.value end asc nulls last
      )::int as "position",
      count(*) over (partition by a.value) > 1 as is_tied
    from population p
    join agg a on a.athlete_id = p.athlete_id
  )
  select r."position", r.athlete_id, r.first_name, r.last_name,
         r.value, r.record_count, r.is_tied,
         null::int as previous_position
  from ranked r
  -- The minimum-population guard: below it, nothing is returned at all rather than a
  -- ranking of one or two identifiable people. screens/leaderboards.md, the guard is
  -- "not only statistical" — see migration 0016's header above this function.
  where (select count(*) from ranked) >= greatest(md.min_population, 3)
    -- The final gate: a non-staff caller only ever receives rows if their own
    -- athlete_id is actually in this ranking. This is what makes admin's call return
    -- nothing (no athlete_id to match) without any admin-specific branch.
    and (v_is_staff or exists (select 1 from ranked x where x.athlete_id = v_caller_athlete))
  order by r."position", r.last_name;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.default_threshold_set()
 RETURNS TABLE(name text, description text, domain flag_domain, metric text, comparison threshold_comparison, value numeric, baseline_type baseline_type, baseline_days integer, consecutive_days integer, min_baseline_observations integer, cooldown_days integer, severity flag_severity, notify_roles app_role[], is_active boolean)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  values
    -- The headline rule. z_score against the athlete's own 28-day norm rather than an
    -- absolute readiness number, which is 04-data-model.md §10's whole argument: "an
    -- athlete who consistently sleeps 6.5 hours is not in trouble, an athlete who normally
    -- sleeps 8.5 and slept 6.5 is." consecutive_days 2 so one bad night is not an alert.
    ('Readiness below personal norm',
     'Composite readiness more than 1.5 SD below own 28 day norm',
     'wellness'::public.flag_domain, 'wellness.readiness_score',
     'z_score'::public.threshold_comparison, -1.5::numeric(10,3),
     'personal_rolling'::public.baseline_type, 28, 2, 10, 3,
     'high'::public.flag_severity, '{coach,medical}'::public.app_role[], true),

    ('Sleep dropped',
     'Sleep more than 20 per cent below own 28 day mean, two days running',
     'wellness'::public.flag_domain, 'wellness.sleep_hours',
     'pct_change_below'::public.threshold_comparison, 20::numeric(10,3),
     'personal_rolling'::public.baseline_type, 28, 2, 10, 3,
     'medium'::public.flag_severity, '{coach}'::public.app_role[], true),

    -- Absolute, not personal_rolling, and correctly so: soreness is a 1-5 self-report where
    -- 2-or-below means the same thing for every athlete. baseline_days null and
    -- min_baseline_observations 0 because an absolute rule needs no baseline to be valid.
    -- Safe to ship live in a club's first week despite that, unlike the compliance rule
    -- below: a day with no wellness entry has no soreness value at all, so 0053 treats it
    -- as a gap and the rule needs three REAL self-reports at 2-or-below before it fires.
    ('Soreness elevated',
     'Soreness at 2 or below for three days running',
     'wellness'::public.flag_domain, 'wellness.soreness',
     'below'::public.threshold_comparison, 2::numeric(10,3),
     'absolute'::public.baseline_type, null, 3, 0, 2,
     'medium'::public.flag_severity, '{coach,medical}'::public.app_role[], true),

    -- Absolute, matching what 0052 actually evaluates: `above` is a flat comparison
    -- against this row's own value and never reads a mean or an SD, whatever
    -- baseline_type says. The original row said 'personal_rolling' with
    -- min_baseline_observations 14, which changed nothing about the trip condition and
    -- only made the rule silently dormant for an athlete's first 14 ACWR observations —
    -- see correction (b) in this file's header, and the description, which used to
    -- describe a personal 1SD band this rule has never evaluated.
    -- The new-club protection this looks like it loses, it never had: ACWR itself is
    -- suppressed (NULL, not an estimate) until 21 of the trailing 28 days carry a
    -- training entry, 0052's _threshold_acwr_value, so there is no value to compare
    -- against 1.30 until a club has about a month of real load behind it.
    ('Acute chronic ratio high',
     'Acute:chronic workload ratio above 1.30 — the trailing 7 day load against the 28 day average',
     'gps'::public.flag_domain, 'load.acwr',
     'above'::public.threshold_comparison, 1.30::numeric(10,3),
     'absolute'::public.baseline_type, null, 1, 0, 3,
     'high'::public.flag_severity, '{coach}'::public.app_role[], true),

    -- Low severity and a 7-day cooldown on purpose. A missing wellness entry is an
    -- administrative problem, not a health one, and raising it daily at medium is the
    -- alert-fatigue mechanism 03-flows.md §5 warns about.
    -- SHIPS INACTIVE, and this is the one rule in the set that does. compliance.wellness_7d
    -- is a count, so "no entries" reads as 0 rather than as no observation, and 0 breaches
    -- "below 4" on every day of a club's pre-history. No parameter on this row can tell a
    -- squad that stopped logging from one that has not started — not
    -- min_baseline_observations (the metric is never null, so the count is always full),
    -- not consecutive_days (every prior day breaches too), not 0053's gap tolerance
    -- (there are no gaps in a count). Correction (a) in the header has the whole
    -- argument, including the engine-side follow-up that would let it ship live.
    ('Wellness compliance low',
     'Fewer than four wellness submissions in the last seven days. Starts switched off: '
     'turn it on once the squad has been logging for a couple of weeks, or it will flag '
     'everyone for the entries they had no chance to make yet.',
     'compliance'::public.flag_domain, 'compliance.wellness_7d',
     'below'::public.threshold_comparison, 4::numeric(10,3),
     'absolute'::public.baseline_type, null, 1, 0, 7,
     'low'::public.flag_severity, '{coach}'::public.app_role[], false);
$function$
;
CREATE OR REPLACE FUNCTION public.resolve_my_assigned_sessions_by_week(p_athlete_id uuid, p_from date, p_to date)
 RETURNS TABLE(week_start date, assigned integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_athlete uuid;
begin
  if auth_has_any_role(array['coach','medical']::app_role[]) then
    v_athlete := p_athlete_id;
  elsif auth_has_any_role(array['athlete']::app_role[]) and auth_athlete_id() = p_athlete_id then
    v_athlete := p_athlete_id;
  else
    v_athlete := null;
  end if;

  if v_athlete is null or p_from is null or p_to is null or p_to < p_from then
    return;
  end if;

  -- A span nothing on screen can use. The caller asks for four weeks; this is
  -- a ceiling, not a feature, so a caller that asks for two years gets nothing
  -- back rather than a scan of every block in the org.
  if p_to - p_from > 400 then
    return;
  end if;

  return query
  with weeks as (
    select generate_series(
             date_trunc('week', p_from::timestamp)::date,
             date_trunc('week', p_to::timestamp)::date,
             interval '7 day'
           )::date as ws
  ),
  mine as (
    select pa.id,
           pa.programme_id,
           date_trunc('week', pa.starts_on::timestamp)::date as anchor,
           pa.starts_on,
           pa.ends_on
    from programme_assignments pa
    join programmes pr on pr.id = pa.programme_id
    where pa.org_id = auth_org_id()
      -- 'completed' is included on purpose: the window looks backwards, and a
      -- block that finished last week still assigned work while it ran.
      -- 'suspended' and 'cancelled' are not — a suspended assignment (a rehab
      -- programme displacing a gym one) was not asking for anything.
      and pa.status in ('active', 'completed')
      and pr.programme_type <> 'nutrition'
      and (
        pa.athlete_id = v_athlete
        or (pa.group_id is not null and exists (
              select 1
              from group_memberships gm
              where gm.athlete_id = v_athlete
                and gm.group_id = pa.group_id
                and gm.removed_at is null))
      )
  ),
  spans as (
    select b.programme_id,
           b.id as block_id,
           b.duration_weeks,
           sum(b.duration_weeks) over (
             partition by b.programme_id
             order by b.sequence
             rows between unbounded preceding and current row
           ) as cum_end
    from programme_blocks b
  ),
  placed as (
    select w.ws,
           sp.block_id,
           ((w.ws - m.anchor) / 7) - (sp.cum_end - sp.duration_weeks) + 1 as week_in_block
    from weeks w
    join mine m
      on w.ws >= m.anchor
     and m.starts_on <= w.ws + 6
     and (m.ends_on is null or m.ends_on >= w.ws)
    join spans sp
      on sp.programme_id = m.programme_id
     and ((w.ws - m.anchor) / 7) >= (sp.cum_end - sp.duration_weeks)
     and ((w.ws - m.anchor) / 7) <  sp.cum_end
  )
  select w.ws,
         coalesce((
           select count(distinct s.id)::int
           from placed p
           join programme_sessions s
             on s.block_id = p.block_id
            and s.week_number = p.week_in_block
           where p.ws = w.ws
         ), 0)
  from weeks w
  order by w.ws;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.resolve_my_programme_sessions(p_athlete_id uuid)
 RETURNS TABLE(programme_id uuid, programme_name text, programme_type programme_type, block_name text, block_sequence integer, session_id uuid, session_name text, week_number integer, day_number integer, md_offset integer, session_sequence integer)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_athlete uuid;
begin
  if auth_has_any_role(array['coach','medical']::app_role[]) then
    v_athlete := p_athlete_id;
  elsif auth_has_any_role(array['athlete']::app_role[]) and auth_athlete_id() = p_athlete_id then
    v_athlete := p_athlete_id;
  else
    v_athlete := null;
  end if;

  if v_athlete is null then
    return;
  end if;

  return query
  select distinct p.id, p.name, p.programme_type, b.name, b.sequence,
         s.id, s.name, s.week_number, s.day_number, s.md_offset, s.sequence
  from programme_assignments pa
  join programmes p on p.id = pa.programme_id
  join programme_blocks b on b.programme_id = p.id
  join programme_sessions s on s.block_id = b.id
  where pa.org_id = auth_org_id()
    and pa.status = 'active'
    -- The fix: a draft programme was never excluded here before. Spec says
    -- "A draft programme is invisible to athletes" (programme-builder.md,
    -- Publishing); the code just never enforced it.
    and p.status = 'active'
    and (
      pa.athlete_id = v_athlete
      or (pa.group_id is not null and exists (
            select 1 from group_memberships gm
            where gm.athlete_id = v_athlete
              and gm.group_id = pa.group_id
              and gm.removed_at is null))
    )
  order by b.sequence, s.week_number, s.sequence;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.resolve_nutrition_targets(p_athlete_ids uuid[], p_from date, p_to date)
 RETURNS TABLE(athlete_id uuid, target_date date, md_offset integer, energy_kcal numeric, protein_g numeric, carbs_g numeric, fat_g numeric, fluid_ml numeric, tolerance_pct numeric, source_scope text, source_id uuid, md_specific boolean)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_ids uuid[];
begin
  if auth_has_any_role(array['coach','medical']::app_role[]) then
    v_ids := p_athlete_ids;
  elsif auth_has_any_role(array['athlete']::app_role[]) then
    v_ids := array[auth_athlete_id()];
  else
    v_ids := array[]::uuid[];
  end if;

  return query
  with days as (
    select d::date as target_date
    from generate_series(p_from, p_to, interval '1 day') d
  ),
  md as (
    select d.target_date,
           (select s.md_offset from sessions s
            where s.org_id = auth_org_id()
              and s.starts_at::date = d.target_date
              and s.deleted_at is null
              and s.md_offset is not null
            order by s.starts_at limit 1) as md_offset
    from days d
  ),
  ath as (select unnest(v_ids) as athlete_id),
  candidates as (
    select
      a.athlete_id           as c_athlete_id,
      m.target_date          as c_target_date,
      m.md_offset            as c_md_offset,
      t.id                   as c_id,
      t.athlete_id           as t_athlete_id,
      t.group_id             as t_group_id,
      t.org_default          as t_org_default,
      t.energy_kcal          as t_energy_kcal,
      t.protein_g            as t_protein_g,
      t.carbs_g              as t_carbs_g,
      t.fat_g                as t_fat_g,
      t.fluid_ml             as t_fluid_ml,
      t.tolerance_pct        as t_tolerance_pct,
      t.effective_from       as t_effective_from,
      case
        when t.athlete_id is not null and t.md_offset is not null then 1
        when t.athlete_id is not null                             then 2
        when t.group_id  is not null and t.md_offset is not null  then 3
        when t.group_id  is not null                              then 4
        when t.org_default and t.md_offset is not null            then 5
        else 6
      end as precedence,
      coalesce(g.sort_order, 0) as group_sort
    from ath a
    cross join md m
    join nutrition_targets t
      on t.org_id = auth_org_id()
     and t.deleted_at is null
     and t.effective_from <= m.target_date
     and (t.effective_to is null or t.effective_to >= m.target_date)
     and (t.md_offset is null or t.md_offset = m.md_offset)
     and (
          t.athlete_id = a.athlete_id
       or (t.group_id is not null and exists (
             select 1 from group_memberships gm
             where gm.athlete_id = a.athlete_id
               and gm.group_id = t.group_id
               and gm.added_at::date <= m.target_date
               and (gm.removed_at is null or gm.removed_at::date > m.target_date)))
       or t.org_default
     )
    left join groups g on g.id = t.group_id
  ),
  ranked as (
    select *, row_number() over (
      partition by c_athlete_id, c_target_date
      order by precedence, group_sort, t_effective_from desc
    ) as rn
    from candidates
  )
  select
    r.c_athlete_id, r.c_target_date, r.c_md_offset,
    r.t_energy_kcal, r.t_protein_g, r.t_carbs_g, r.t_fat_g, r.t_fluid_ml,
    coalesce(r.t_tolerance_pct, 10) as tolerance_pct,
    case
      when r.precedence <= 2 then 'personal'
      when r.precedence <= 4 then 'group'
      when r.precedence <= 6 then 'squad_default'
    end as source_scope,
    r.c_id as source_id,
    (r.precedence in (1,3,5)) as md_specific
  from ranked r
  where r.rn = 1;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.resolve_programme_exercises(p_programme_session_id uuid, p_athlete_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(programme_exercise_id uuid, sequence integer, superset_group text, exercise_id uuid, exercise_name text, category exercise_category, sets integer, reps_min integer, reps_max integer, load_basis load_basis, load_value numeric, tempo text, rest_seconds integer, notes text, is_overridden boolean, is_exempt boolean, override_types override_type[], override_reason text, one_rm_linked boolean, resolved_load_kg numeric, one_rm_missing boolean, one_rm_test_date date)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org uuid := auth_org_id();
  v_allowed boolean := false;
  v_target_athlete uuid := null;
begin
  if auth_has_any_role(array['coach','medical']::app_role[]) then
    v_allowed := exists (
      select 1 from programme_sessions s
        join programme_blocks b on b.id = s.block_id
        join programmes p on p.id = b.programme_id
      where s.id = p_programme_session_id and p.org_id = v_org
    );
    -- Staff may ask for a specific athlete's resolution, or pass null for the
    -- squad-generic parent view unchanged from before this migration.
    v_target_athlete := p_athlete_id;
  elsif auth_has_any_role(array['athlete']::app_role[]) then
    v_allowed := exists (
      select 1 from programme_sessions s
        join programme_blocks b on b.id = s.block_id
        join programmes p on p.id = b.programme_id
        join programme_assignments pa on pa.programme_id = p.id
      where s.id = p_programme_session_id
        and pa.org_id = v_org
        and pa.status = 'active'
        and (
          pa.athlete_id = auth_athlete_id()
          or (pa.group_id is not null and exists (
                select 1 from group_memberships gm
                where gm.athlete_id = auth_athlete_id()
                  and gm.group_id = pa.group_id
                  and gm.removed_at is null))
        )
    );
    -- An athlete resolves only themselves, whatever p_athlete_id the caller
    -- passed — same stance resolve_my_programme_sessions already takes.
    v_target_athlete := auth_athlete_id();
  end if;

  if not v_allowed then
    return;
  end if;

  if v_target_athlete is null then
    return query
    select pe.id, pe.sequence, pe.superset_group, e.id, e.name, e.category,
           pe.sets, pe.reps_min, pe.reps_max, pe.load_basis, pe.load_value,
           pe.tempo, pe.rest_seconds, pe.notes,
           false, false, array[]::override_type[], null::text,
           (e.one_rm_test_definition_id is not null), null::numeric, null::boolean, null::date
    from programme_exercises pe
    join exercises e on e.id = pe.exercise_id
    where pe.programme_session_id = p_programme_session_id
    order by pe.sequence;
    return;
  end if;

  return query
  with pe as (
    select * from programme_exercises where programme_session_id = p_programme_session_id
  ),
  ov as (
    select o.* from exercise_overrides o
    join pe on pe.id = o.programme_exercise_id
    where o.athlete_id = v_target_athlete
      and o.org_id = v_org
      and (o.expires_at is null or o.expires_at > now())
  ),
  resolved as (
    select
      pe.id                                             as pe_id,
      pe.sequence                                        as pe_sequence,
      pe.superset_group                                  as pe_superset,
      coalesce(sub.substitute_exercise_id, pe.exercise_id) as resolved_exercise_id,
      coalesce(vol.sets, pe.sets)                        as r_sets,
      coalesce(vol.reps_min, pe.reps_min)                as r_reps_min,
      coalesce(vol.reps_max, pe.reps_max)                as r_reps_max,
      pe.load_basis                                      as pe_load_basis,
      case when cap.load_value is not null
           then least(pe.load_value, cap.load_value)
           else pe.load_value end                        as r_load_value,
      pe.tempo                                            as pe_tempo,
      pe.rest_seconds                                    as pe_rest,
      pe.notes                                            as pe_notes,
      (ex.id is not null)                                as r_is_exempt,
      (sub.id is not null or vol.id is not null or cap.id is not null or nt.id is not null) as r_is_overridden,
      array_remove(array[
        case when ex.id  is not null then 'exempt'::override_type end,
        case when sub.id is not null then 'substitute'::override_type end,
        case when vol.id is not null then 'volume'::override_type end,
        case when cap.id is not null then 'load_cap'::override_type end,
        case when nt.id  is not null then 'note'::override_type end
      ], null)                                            as r_override_types,
      coalesce(ex.reason, sub.reason, vol.reason, cap.reason, nt.reason) as r_override_reason
    from pe
    left join ov ex  on ex.programme_exercise_id  = pe.id and ex.override_type  = 'exempt'
    left join ov sub on sub.programme_exercise_id = pe.id and sub.override_type = 'substitute'
    left join ov vol on vol.programme_exercise_id = pe.id and vol.override_type = 'volume'
    left join ov cap on cap.programme_exercise_id = pe.id and cap.override_type = 'load_cap'
    left join ov nt  on nt.programme_exercise_id  = pe.id and nt.override_type  = 'note'
  )
  select
    r.pe_id, r.pe_sequence, r.pe_superset,
    e.id, e.name, e.category,
    r.r_sets, r.r_reps_min, r.r_reps_max,
    r.pe_load_basis, r.r_load_value, r.pe_tempo, r.pe_rest, r.pe_notes,
    r.r_is_overridden, r.r_is_exempt, r.r_override_types, r.r_override_reason,
    (e.one_rm_test_definition_id is not null),
    case when r.pe_load_basis = 'percent_1rm' and r.r_load_value is not null and best.value is not null
         then round(r.r_load_value * best.value / 100.0, 1)
         else null end,
    (r.pe_load_basis = 'percent_1rm' and (e.one_rm_test_definition_id is null or best.value is null)),
    best.test_date
  from resolved r
  join exercises e on e.id = r.resolved_exercise_id
  left join lateral (
    select tr.value, tr.test_date
    from test_results tr
    where e.one_rm_test_definition_id is not null
      and tr.athlete_id = v_target_athlete
      and tr.org_id = v_org
      and tr.test_definition_id = e.one_rm_test_definition_id
      and tr.deleted_at is null
      and tr.is_best
    order by tr.test_date desc
    limit 1
  ) best on true
  where not r.r_is_exempt
  order by r.pe_sequence;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.revise_training_entry(p_original_id uuid, p_new_id uuid, p_payload jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org      uuid := public.auth_org_id();
  v_original public.training_entries;
  v_is_staff boolean := public.auth_has_any_role(array['coach','medical']::public.app_role[]);
  v_new_id   uuid;
  v_before   jsonb;
  v_after    jsonb;
  v_changes  jsonb := '{}'::jsonb;
  v_key      text;
begin
  if v_org is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;

  select * into v_original
  from public.training_entries
  where id = p_original_id
    and org_id = v_org
    and superseded_by is null;

  if v_original.id is null then
    raise exception 'entry_not_revisable' using errcode = 'P0001';
  end if;

  -- Same narrowing as revise_wellness_entry above; see that function for the
  -- reasoning, which applies here unchanged.
  if not v_is_staff then
    raise exception 'not_permitted' using errcode = 'P0001';
  end if;

  -- Close the original first, for the same reason as revise_wellness_entry.
  update public.training_entries
     set superseded_by = p_new_id
   where id = p_original_id;

  -- session_load is not written here on purpose: the training_entries_session_load
  -- trigger (0010) recomputes rpe x duration_min on the inserted row, so a corrected
  -- RPE or duration produces a corrected load without this function knowing the
  -- formula. Unchanged from 0010, restated because a reader of a coach-facing
  -- correction naturally asks where the load went.
  insert into public.training_entries (
    id, org_id, athlete_id, session_id, entry_date,
    rpe, duration_min, comment,
    source, submitted_at, revision_of, created_by
  )
  values (
    p_new_id, v_original.org_id, v_original.athlete_id, v_original.session_id,
    v_original.entry_date,
    coalesce((p_payload ->> 'rpe')::numeric,      v_original.rpe),
    coalesce((p_payload ->> 'duration_min')::int, v_original.duration_min),
    coalesce( p_payload ->> 'comment',            v_original.comment),
    v_original.source, now(), v_original.id, public.auth_user_id()
  )
  returning id into v_new_id;

  -- The same in-transaction audit event as revise_wellness_entry; see that function and
  -- this migration's header for the reasoning, which applies here unchanged.
  --
  -- One difference worth naming: session_load is recomputed by a trigger and is NOT a
  -- payload key, so it never appears in `changed`. The audit records what the coach
  -- asked to change (rpe, duration_min); the derived load that followed is on the row.
  v_before := to_jsonb(v_original);
  select to_jsonb(t) into v_after from public.training_entries t where t.id = v_new_id;

  -- The typeof guard is not defensive padding: jsonb_object_keys RAISES on a scalar,
  -- where every other read of p_payload above degrades to null. A caller passing
  -- '"oops"'::jsonb would otherwise write the revision and then fail on the audit, which
  -- is the one shape of failure this whole change exists to prevent.
  if jsonb_typeof(p_payload) = 'object' then
    for v_key in select t.k from jsonb_object_keys(p_payload) as t(k)
    loop
      if v_before ? v_key and (v_before -> v_key) is distinct from (v_after -> v_key) then
        v_changes := v_changes || jsonb_build_object(
          v_key, jsonb_build_object('from', v_before -> v_key, 'to', v_after -> v_key));
      end if;
    end loop;
  end if;

  if pg_column_size(v_changes) > 8192 then
    v_changes := jsonb_build_object(
      'fields',         (select jsonb_agg(t.k) from jsonb_object_keys(v_changes) as t(k)),
      'values_omitted', true);
  end if;

  perform public.write_audit_event(
    'entry_revision.created',
    'training_entry',
    v_new_id,
    v_original.athlete_id,
    jsonb_build_object(
      'domain',      'training',
      'entry_date',  v_original.entry_date,
      'session_id',  v_original.session_id,
      'superseded',  v_original.id,
      'changed',     v_changes
    )
  );

  return v_new_id;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.revise_wellness_entry(p_original_id uuid, p_new_id uuid, p_payload jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org      uuid := public.auth_org_id();
  v_original public.wellness_entries;
  v_is_staff boolean := public.auth_has_any_role(array['coach','medical']::public.app_role[]);
  v_new_id   uuid;
  v_before   jsonb;
  v_after    jsonb;
  v_changes  jsonb := '{}'::jsonb;
  v_key      text;
begin
  if v_org is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;

  select * into v_original
  from public.wellness_entries
  where id = p_original_id
    and org_id = v_org
    and superseded_by is null;      -- check 1 (tenancy) and check 3 (linear chain)

  if v_original.id is null then
    raise exception 'entry_not_revisable' using errcode = 'P0001';
  end if;

  -- check 2, narrowed by this migration. Was: athlete-themselves OR staff.
  -- The athlete branch is gone entirely — an athlete calling this for their own
  -- entry now gets the same not_permitted as anyone else. Deliberately checked
  -- AFTER the row lookup so that a staff caller and an athlete caller cannot
  -- distinguish "wrong id" from "not allowed" by timing the two error paths any
  -- differently than 0010 already did.
  if not v_is_staff then
    raise exception 'not_permitted' using errcode = 'P0001';
  end if;

  -- Close the original first. The partial unique index permits one live row per
  -- athlete per day, so the new revision cannot land until this one is closed. The
  -- foreign key on superseded_by is deferred, which is what makes forward
  -- referencing p_new_id legal.
  update public.wellness_entries
     set superseded_by = p_new_id
   where id = p_original_id;

  -- check 4: identity columns come from the original, never from p_payload.
  -- `source` is copied too, unchanged from 0010: a coach fixing a mis-typed sleep
  -- value does not turn the athlete's self_report into a staff observation. What the
  -- row carries about who did the correcting is created_by, which is the acting
  -- staff user. Both facts matter and they are stored in the two columns that mean
  -- them, rather than one being overwritten to imply the other.
  insert into public.wellness_entries (
    id, org_id, athlete_id, entry_date,
    sleep_hours, sleep_quality, fatigue, soreness, soreness_areas,
    stress, mood, resting_hr, body_mass_kg, comment,
    source, submitted_at, revision_of, created_by
  )
  values (
    p_new_id, v_original.org_id, v_original.athlete_id, v_original.entry_date,
    coalesce((p_payload ->> 'sleep_hours')::numeric,  v_original.sleep_hours),
    coalesce((p_payload ->> 'sleep_quality')::int,    v_original.sleep_quality),
    coalesce((p_payload ->> 'fatigue')::int,          v_original.fatigue),
    coalesce((p_payload ->> 'soreness')::int,         v_original.soreness),
    coalesce(
      case when jsonb_typeof(p_payload -> 'soreness_areas') = 'array'
           then array(select jsonb_array_elements_text(p_payload -> 'soreness_areas'))
      end, v_original.soreness_areas),
    coalesce((p_payload ->> 'stress')::int,           v_original.stress),
    coalesce((p_payload ->> 'mood')::int,             v_original.mood),
    coalesce((p_payload ->> 'resting_hr')::int,       v_original.resting_hr),
    coalesce((p_payload ->> 'body_mass_kg')::numeric, v_original.body_mass_kg),
    coalesce( p_payload ->> 'comment',                v_original.comment),
    v_original.source, now(), v_original.id, public.auth_user_id()
  )
  returning id into v_new_id;

  -- The audit event. See this migration's header for why it lives here rather than in
  -- the caller. Same transaction as the insert: no committed correction is unaudited.
  v_before := to_jsonb(v_original);
  select to_jsonb(w) into v_after from public.wellness_entries w where w.id = v_new_id;

  -- Only the keys the caller actually sent, and only those that actually moved. Driven
  -- off the payload rather than a hand-written field list so a column added to the
  -- insert above cannot quietly stop being audited; `v_before ? v_key` discards any key
  -- that is not a real column, so a caller cannot pad audit_log with invented fields.
  -- The typeof guard is not defensive padding: jsonb_object_keys RAISES on a scalar,
  -- where every other read of p_payload above degrades to null. A caller passing
  -- '"oops"'::jsonb would otherwise write the revision and then fail on the audit, which
  -- is the one shape of failure this whole change exists to prevent.
  if jsonb_typeof(p_payload) = 'object' then
    for v_key in select t.k from jsonb_object_keys(p_payload) as t(k)
    loop
      if v_before ? v_key and (v_before -> v_key) is distinct from (v_after -> v_key) then
        v_changes := v_changes || jsonb_build_object(
          v_key, jsonb_build_object('from', v_before -> v_key, 'to', v_after -> v_key));
      end if;
    end loop;
  end if;

  -- 04-data-model.md §13 caps metadata at 16 KB with a check constraint, and `comment`
  -- alone can be 1000 characters twice over. Well short of the cap in practice; if it is
  -- ever reached the event still gets written, carrying which fields changed but not
  -- their old values, because an unwritable audit row would abort a legitimate
  -- correction.
  if pg_column_size(v_changes) > 8192 then
    v_changes := jsonb_build_object(
      'fields',         (select jsonb_agg(t.k) from jsonb_object_keys(v_changes) as t(k)),
      'values_omitted', true);
  end if;

  perform public.write_audit_event(
    'entry_revision.created',
    'wellness_entry',
    v_new_id,
    v_original.athlete_id,
    jsonb_build_object(
      'domain',      'wellness',
      'entry_date',  v_original.entry_date,
      'superseded',  v_original.id,
      'changed',     v_changes
    )
  );

  return v_new_id;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.suspend_assignments_for_rehab(p_athlete_id uuid, p_rehab_programme_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_org uuid := public.auth_org_id();
begin
  if v_org is null then
    raise exception 'not_authenticated' using errcode = 'P0001';
  end if;

  if not public.auth_has_any_role(array['medical']::public.app_role[]) then
    raise exception 'not_permitted' using errcode = 'P0001';
  end if;

  -- The one precondition that keeps this narrow: it only ever suspends
  -- anything when p_rehab_programme_id genuinely is a rehab programme in
  -- the caller's own org — never a general-purpose "medical may suspend
  -- any assignment" escape hatch.
  if not exists (
    select 1 from public.programmes p
    where p.id = p_rehab_programme_id
      and p.org_id = v_org
      and p.programme_type = 'rehab'
      and p.deleted_at is null
  ) then
    raise exception 'not_a_rehab_programme' using errcode = 'P0001';
  end if;

  update public.programme_assignments
     set status = 'suspended', suspended_reason = 'Rehab programme assigned'
   where org_id = v_org
     and athlete_id = p_athlete_id
     and status = 'active'
     and programme_id <> p_rehab_programme_id;
end;
$function$
;

-- Drop the 8 policies the push created and production has never had.
drop policy if exists gps_records_staff_update on public.gps_records;
drop policy if exists injuries_staff_insert on public.injuries;
drop policy if exists nutrition_rules_nutrition_insert on public.nutrition_rules;
drop policy if exists nutrition_rules_nutrition_update on public.nutrition_rules;
drop policy if exists nutrition_targets_nutrition_insert on public.nutrition_targets;
drop policy if exists nutrition_targets_nutrition_update on public.nutrition_targets;
drop policy if exists threshold_revisions_staff_select on public.threshold_revisions;
drop policy if exists thresholds_staff_select on public.thresholds;

-- Restore the 128 policies the push altered, and the 11 it removed.
drop policy if exists athlete_consents_admin_select on public.athlete_consents;
create policy athlete_consents_admin_select on public.athlete_consents
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists athlete_consents_admin_update on public.athlete_consents;
create policy athlete_consents_admin_update on public.athlete_consents
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])))
  with check (((org_id = auth_org_id()) AND consent_write_allowed(purpose, granted_at, withdrawn_at)));
drop policy if exists athlete_consents_admin_write on public.athlete_consents;
create policy athlete_consents_admin_write on public.athlete_consents
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role]) AND consent_write_allowed(purpose, granted_at, withdrawn_at)));
drop policy if exists athletes_manage_insert on public.athletes;
create policy athletes_manage_insert on public.athletes
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role])));
drop policy if exists athletes_manage_update on public.athletes;
create policy athletes_manage_update on public.athletes
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists athletes_staff_select on public.athletes;
create policy athletes_staff_select on public.athletes
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists audit_admin_select on public.audit_log;
create policy audit_admin_select on public.audit_log
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists availability_coach_insert_noninjury on public.availability;
create policy availability_coach_insert_noninjury on public.availability
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (set_by = auth_user_id()) AND (injury_id IS NULL) AND (reason_category IS NOT NULL) AND (reason_category IS DISTINCT FROM 'injury'::availability_reason)));
drop policy if exists availability_coach_update_noninjury on public.availability;
create policy availability_coach_update_noninjury on public.availability
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (injury_id IS NULL) AND (reason_category IS DISTINCT FROM 'injury'::availability_reason)))
  with check (((org_id = auth_org_id()) AND (injury_id IS NULL) AND (reason_category IS DISTINCT FROM 'injury'::availability_reason)));
drop policy if exists availability_medical_insert on public.availability;
create policy availability_medical_insert on public.availability
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (set_by = auth_user_id())));
drop policy if exists availability_medical_update on public.availability;
create policy availability_medical_update on public.availability
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists availability_staff_select on public.availability;
create policy availability_staff_select on public.availability
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists body_composition_staff_insert on public.body_composition;
create policy body_composition_staff_insert on public.body_composition
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (recorded_by = auth_user_id())));
drop policy if exists body_composition_staff_select on public.body_composition;
create policy body_composition_staff_select on public.body_composition
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists body_composition_staff_update on public.body_composition;
create policy body_composition_staff_update on public.body_composition
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists body_mass_target_ranges_staff_insert on public.body_mass_target_ranges;
create policy body_mass_target_ranges_staff_insert on public.body_mass_target_ranges
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (set_by = auth_user_id()) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM athletes a
  WHERE ((a.id = body_mass_target_ranges.athlete_id) AND (a.org_id = auth_org_id()) AND (a.deleted_at IS NULL))))));
drop policy if exists body_mass_target_ranges_staff_select on public.body_mass_target_ranges;
create policy body_mass_target_ranges_staff_select on public.body_mass_target_ranges
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists body_mass_target_ranges_staff_update on public.body_mass_target_ranges;
create policy body_mass_target_ranges_staff_update on public.body_mass_target_ranges
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists compliance_staff_insert on public.compliance_expectations;
create policy compliance_staff_insert on public.compliance_expectations
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists compliance_staff_select on public.compliance_expectations;
create policy compliance_staff_select on public.compliance_expectations
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists compliance_staff_update on public.compliance_expectations;
create policy compliance_staff_update on public.compliance_expectations
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists exercise_overrides_staff_select on public.exercise_overrides;
create policy exercise_overrides_staff_select on public.exercise_overrides
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists exercise_overrides_update on public.exercise_overrides;
create policy exercise_overrides_update on public.exercise_overrides
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM (((programme_exercises pe
     JOIN programme_sessions s ON ((s.id = pe.programme_session_id)))
     JOIN programme_blocks b ON ((b.id = s.block_id)))
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((pe.id = exercise_overrides.programme_exercise_id) AND (p.org_id = auth_org_id()) AND (auth_has_any_role(ARRAY['coach'::app_role]) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists exercise_overrides_write on public.exercise_overrides;
create policy exercise_overrides_write on public.exercise_overrides
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (created_by = auth_user_id()) AND (EXISTS ( SELECT 1
   FROM (((programme_exercises pe
     JOIN programme_sessions s ON ((s.id = pe.programme_session_id)))
     JOIN programme_blocks b ON ((b.id = s.block_id)))
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((pe.id = exercise_overrides.programme_exercise_id) AND (p.org_id = auth_org_id()) AND (auth_has_any_role(ARRAY['coach'::app_role]) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists exercises_staff_insert on public.exercises;
create policy exercises_staff_insert on public.exercises
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists exercises_staff_update on public.exercises;
create policy exercises_staff_update on public.exercises
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists fixtures_staff_insert on public.fixtures;
create policy fixtures_staff_insert on public.fixtures
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists fixtures_staff_update on public.fixtures;
create policy fixtures_staff_update on public.fixtures
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists flag_actions_staff_insert on public.flag_actions;
create policy flag_actions_staff_insert on public.flag_actions
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (taken_by = auth_user_id())));
drop policy if exists flag_actions_staff_select on public.flag_actions;
create policy flag_actions_staff_select on public.flag_actions
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists flags_staff_insert on public.flags;
create policy flags_staff_insert on public.flags
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists flags_staff_select on public.flags;
create policy flags_staff_select on public.flags
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists flags_staff_update on public.flags;
create policy flags_staff_update on public.flags
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists gps_records_staff_insert on public.gps_records;
create policy gps_records_staff_insert on public.gps_records
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists gps_records_staff_select on public.gps_records;
create policy gps_records_staff_select on public.gps_records
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists group_memberships_staff_insert on public.group_memberships;
create policy group_memberships_staff_insert on public.group_memberships
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (auth_has_any_role(ARRAY['medical'::app_role]) OR (auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role]) AND (NOT (EXISTS ( SELECT 1
   FROM groups g
  WHERE ((g.id = group_memberships.group_id) AND (g.org_id = auth_org_id()) AND (g.group_type = 'rehab'::group_type)))))))));
drop policy if exists group_memberships_staff_select on public.group_memberships;
create policy group_memberships_staff_select on public.group_memberships
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists group_memberships_staff_update on public.group_memberships;
create policy group_memberships_staff_update on public.group_memberships
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])))
  with check (((org_id = auth_org_id()) AND (auth_has_any_role(ARRAY['medical'::app_role]) OR (auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role]) AND (NOT (EXISTS ( SELECT 1
   FROM groups g
  WHERE ((g.id = group_memberships.group_id) AND (g.org_id = auth_org_id()) AND (g.group_type = 'rehab'::group_type)))))))));
drop policy if exists groups_staff_insert on public.groups;
create policy groups_staff_insert on public.groups
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists groups_staff_update on public.groups;
create policy groups_staff_update on public.groups
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists gym_session_logs_staff_select on public.gym_session_logs;
create policy gym_session_logs_staff_select on public.gym_session_logs
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists gym_set_logs_staff_select on public.gym_set_logs;
create policy gym_set_logs_staff_select on public.gym_set_logs
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists import_batches_staff_insert on public.import_batches;
create policy import_batches_staff_insert on public.import_batches
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (imported_by = auth_user_id())));
drop policy if exists import_batches_staff_select on public.import_batches;
create policy import_batches_staff_select on public.import_batches
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists injuries_medical_update on public.injuries;
create policy injuries_medical_update on public.injuries
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists injuries_staff_select on public.injuries;
create policy injuries_staff_select on public.injuries
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists clinical_medical_only on public.injury_clinical;
create policy clinical_medical_only on public.injury_clinical
  as permissive
  for all
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])))
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])));
drop policy if exists leaderboard_opt_outs_medical_insert on public.leaderboard_opt_outs;
create policy leaderboard_opt_outs_medical_insert on public.leaderboard_opt_outs
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (opt_out_source = 'medical'::text) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (opted_out_by = auth_user_id())));
drop policy if exists leaderboard_opt_outs_staff_select on public.leaderboard_opt_outs;
create policy leaderboard_opt_outs_staff_select on public.leaderboard_opt_outs
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists leaderboard_opt_outs_staff_update on public.leaderboard_opt_outs;
create policy leaderboard_opt_outs_staff_update on public.leaderboard_opt_outs
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists leaderboards_staff_insert on public.leaderboards;
create policy leaderboards_staff_insert on public.leaderboards
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists leaderboards_staff_select on public.leaderboards;
create policy leaderboards_staff_select on public.leaderboards
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists leaderboards_staff_update on public.leaderboards;
create policy leaderboards_staff_update on public.leaderboards
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists login_attempts_admin_select on public.login_attempts;
create policy login_attempts_admin_select on public.login_attempts
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists meal_library_coach_insert on public.meal_library;
create policy meal_library_coach_insert on public.meal_library
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (created_by = auth_user_id())));
drop policy if exists meal_library_coach_update on public.meal_library;
create policy meal_library_coach_update on public.meal_library
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists meal_library_staff_select on public.meal_library;
create policy meal_library_staff_select on public.meal_library
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists meal_library_items_coach_insert on public.meal_library_items;
create policy meal_library_items_coach_insert on public.meal_library_items
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (EXISTS ( SELECT 1
   FROM meal_library m
  WHERE ((m.id = meal_library_items.meal_id) AND (m.org_id = auth_org_id()) AND (m.deleted_at IS NULL))))));
drop policy if exists meal_library_items_staff_select on public.meal_library_items;
create policy meal_library_items_staff_select on public.meal_library_items
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists nutrition_checkins_staff_select on public.nutrition_checkins;
create policy nutrition_checkins_staff_select on public.nutrition_checkins
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists nutrition_rules_staff_select on public.nutrition_rules;
create policy nutrition_rules_staff_select on public.nutrition_rules
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists nutrition_targets_staff_select on public.nutrition_targets;
create policy nutrition_targets_staff_select on public.nutrition_targets
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists organisations_admin_update on public.organisations;
create policy organisations_admin_update on public.organisations
  as permissive
  for update
  to authenticated
  using (((id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])))
  with check ((id = auth_org_id()));
drop policy if exists problem_report_notes_medical_insert on public.problem_report_notes;
create policy problem_report_notes_medical_insert on public.problem_report_notes
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (created_by = auth_user_id()) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM problem_reports pr
  WHERE ((pr.id = problem_report_notes.report_id) AND (pr.org_id = auth_org_id()) AND (pr.deleted_at IS NULL))))));
drop policy if exists problem_report_notes_medical_select on public.problem_report_notes;
create policy problem_report_notes_medical_select on public.problem_report_notes
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])));
drop policy if exists problem_reports_medical_select on public.problem_reports;
create policy problem_reports_medical_select on public.problem_reports
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])));
drop policy if exists problem_reports_medical_update on public.problem_reports;
create policy problem_reports_medical_update on public.problem_reports
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists programme_assignments_staff_select on public.programme_assignments;
create policy programme_assignments_staff_select on public.programme_assignments
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists programme_assignments_update on public.programme_assignments;
create policy programme_assignments_update on public.programme_assignments
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM programmes p
  WHERE ((p.id = programme_assignments.programme_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_assignments_write on public.programme_assignments;
create policy programme_assignments_write on public.programme_assignments
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (assigned_by = auth_user_id()) AND (EXISTS ( SELECT 1
   FROM programmes p
  WHERE ((p.id = programme_assignments.programme_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_blocks_staff_select on public.programme_blocks;
create policy programme_blocks_staff_select on public.programme_blocks
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists programme_blocks_update on public.programme_blocks;
create policy programme_blocks_update on public.programme_blocks
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM programmes p
  WHERE ((p.id = programme_blocks.programme_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_blocks_write on public.programme_blocks;
create policy programme_blocks_write on public.programme_blocks
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM programmes p
  WHERE ((p.id = programme_blocks.programme_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_exercises_staff_select on public.programme_exercises;
create policy programme_exercises_staff_select on public.programme_exercises
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists programme_exercises_update on public.programme_exercises;
create policy programme_exercises_update on public.programme_exercises
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM ((programme_sessions s
     JOIN programme_blocks b ON ((b.id = s.block_id)))
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((s.id = programme_exercises.programme_session_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_exercises_write on public.programme_exercises;
create policy programme_exercises_write on public.programme_exercises
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM ((programme_sessions s
     JOIN programme_blocks b ON ((b.id = s.block_id)))
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((s.id = programme_exercises.programme_session_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_sessions_staff_select on public.programme_sessions;
create policy programme_sessions_staff_select on public.programme_sessions
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists programme_sessions_update on public.programme_sessions;
create policy programme_sessions_update on public.programme_sessions
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM (programme_blocks b
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((b.id = programme_sessions.block_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programme_sessions_write on public.programme_sessions;
create policy programme_sessions_write on public.programme_sessions
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (EXISTS ( SELECT 1
   FROM (programme_blocks b
     JOIN programmes p ON ((p.id = b.programme_id)))
  WHERE ((b.id = programme_sessions.block_id) AND (p.org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (p.programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (p.programme_type = 'rehab'::programme_type))))))));
drop policy if exists programmes_staff_select on public.programmes;
create policy programmes_staff_select on public.programmes
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists programmes_update on public.programmes;
create policy programmes_update on public.programmes
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check (((org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (programme_type = 'rehab'::programme_type)))));
drop policy if exists programmes_write on public.programmes;
create policy programmes_write on public.programmes
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND ((auth_has_any_role(ARRAY['coach'::app_role]) AND (programme_type <> 'rehab'::programme_type)) OR (auth_has_any_role(ARRAY['medical'::app_role]) AND (programme_type = 'rehab'::programme_type)))));
drop policy if exists rehab_assignments_medical_insert on public.rehab_assignments;
create policy rehab_assignments_medical_insert on public.rehab_assignments
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (set_by = auth_user_id())));
drop policy if exists rehab_assignments_medical_update on public.rehab_assignments;
create policy rehab_assignments_medical_update on public.rehab_assignments
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists rehab_assignments_staff_select on public.rehab_assignments;
create policy rehab_assignments_staff_select on public.rehab_assignments
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists sar_clinical_reviews_medical_insert on public.sar_clinical_reviews;
create policy sar_clinical_reviews_medical_insert on public.sar_clinical_reviews
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (reviewed_by = auth_user_id()) AND auth_has_any_role(ARRAY['medical'::app_role])));
drop policy if exists sar_clinical_reviews_staff_select on public.sar_clinical_reviews;
create policy sar_clinical_reviews_staff_select on public.sar_clinical_reviews
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role, 'medical'::app_role])));
drop policy if exists sar_requests_admin_insert on public.sar_requests;
create policy sar_requests_admin_insert on public.sar_requests
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND (requested_by = auth_user_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists sar_requests_staff_select on public.sar_requests;
create policy sar_requests_staff_select on public.sar_requests
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role, 'medical'::app_role])));
drop policy if exists sar_requests_staff_update on public.sar_requests;
create policy sar_requests_staff_update on public.sar_requests
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists seasons_staff_insert on public.seasons;
create policy seasons_staff_insert on public.seasons
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists seasons_staff_update on public.seasons;
create policy seasons_staff_update on public.seasons
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists session_attendance_staff_insert on public.session_attendance;
create policy session_attendance_staff_insert on public.session_attendance
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists session_attendance_staff_select on public.session_attendance;
create policy session_attendance_staff_select on public.session_attendance
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists session_attendance_staff_update on public.session_attendance;
create policy session_attendance_staff_update on public.session_attendance
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists session_participants_staff_delete on public.session_participants;
create policy session_participants_staff_delete on public.session_participants
  as permissive
  for delete
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists session_participants_staff_insert on public.session_participants;
create policy session_participants_staff_insert on public.session_participants
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists session_participants_staff_select on public.session_participants;
create policy session_participants_staff_select on public.session_participants
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists sessions_staff_insert on public.sessions;
create policy sessions_staff_insert on public.sessions
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists sessions_staff_update on public.sessions;
create policy sessions_staff_update on public.sessions
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists team_allocations_coach_insert on public.team_allocations;
create policy team_allocations_coach_insert on public.team_allocations
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])));
drop policy if exists team_allocations_coach_update on public.team_allocations;
create policy team_allocations_coach_update on public.team_allocations
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists team_allocations_staff_select on public.team_allocations;
create policy team_allocations_staff_select on public.team_allocations
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists teams_manage_insert on public.teams;
create policy teams_manage_insert on public.teams
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role])));
drop policy if exists teams_manage_update on public.teams;
create policy teams_manage_update on public.teams
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists teams_staff_select on public.teams;
create policy teams_staff_select on public.teams
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists test_definitions_staff_insert on public.test_definitions;
create policy test_definitions_staff_insert on public.test_definitions
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists test_definitions_staff_update on public.test_definitions;
create policy test_definitions_staff_update on public.test_definitions
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists test_results_staff_insert on public.test_results;
create policy test_results_staff_insert on public.test_results
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (recorded_by = auth_user_id())));
drop policy if exists test_results_staff_select on public.test_results;
create policy test_results_staff_select on public.test_results
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists test_results_staff_update on public.test_results;
create policy test_results_staff_update on public.test_results
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists threshold_revisions_coach_insert on public.threshold_revisions;
create policy threshold_revisions_coach_insert on public.threshold_revisions
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (changed_by = auth_user_id())));
drop policy if exists thresholds_coach_insert on public.thresholds;
create policy thresholds_coach_insert on public.thresholds
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])));
drop policy if exists thresholds_coach_update on public.thresholds;
create policy thresholds_coach_update on public.thresholds
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists training_staff_insert on public.training_entries;
create policy training_staff_insert on public.training_entries
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (source = 'staff_entered'::data_source) AND (created_by = auth_user_id())));
drop policy if exists training_staff_select on public.training_entries;
create policy training_staff_select on public.training_entries
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists user_roles_admin_delete on public.user_roles;
create policy user_roles_admin_delete on public.user_roles
  as permissive
  for delete
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists user_roles_admin_insert on public.user_roles;
create policy user_roles_admin_insert on public.user_roles
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists user_roles_admin_update on public.user_roles;
create policy user_roles_admin_update on public.user_roles
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists user_roles_staff_select on public.user_roles;
create policy user_roles_staff_select on public.user_roles
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role, 'admin'::app_role])));
drop policy if exists users_admin_insert on public.users;
create policy users_admin_insert on public.users
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])));
drop policy if exists users_admin_update on public.users;
create policy users_admin_update on public.users
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['admin'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists vendor_profiles_staff_select on public.vendor_profiles;
create policy vendor_profiles_staff_select on public.vendor_profiles
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists week_templates_staff_insert on public.week_templates;
create policy week_templates_staff_insert on public.week_templates
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists week_templates_staff_select on public.week_templates;
create policy week_templates_staff_select on public.week_templates
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists week_templates_staff_update on public.week_templates;
create policy week_templates_staff_update on public.week_templates
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists wellness_staff_insert on public.wellness_entries;
create policy wellness_staff_insert on public.wellness_entries
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role]) AND (source = 'staff_entered'::data_source) AND (created_by = auth_user_id())));
drop policy if exists wellness_staff_select on public.wellness_entries;
create policy wellness_staff_select on public.wellness_entries
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role, 'medical'::app_role])));
drop policy if exists injuries_medical_insert on public.injuries;
create policy injuries_medical_insert on public.injuries
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role])));
drop policy if exists nutrition_rules_coach_insert on public.nutrition_rules;
create policy nutrition_rules_coach_insert on public.nutrition_rules
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (created_by = auth_user_id())));
drop policy if exists nutrition_rules_coach_update on public.nutrition_rules;
create policy nutrition_rules_coach_update on public.nutrition_rules
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists nutrition_rules_medical_insert on public.nutrition_rules;
create policy nutrition_rules_medical_insert on public.nutrition_rules
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (created_by = auth_user_id()) AND (athlete_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM injuries i
  WHERE ((i.athlete_id = nutrition_rules.athlete_id) AND (i.org_id = auth_org_id()) AND (i.status <> 'closed'::injury_status))))));
drop policy if exists nutrition_rules_medical_update on public.nutrition_rules;
create policy nutrition_rules_medical_update on public.nutrition_rules
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (athlete_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM injuries i
  WHERE ((i.athlete_id = nutrition_rules.athlete_id) AND (i.org_id = auth_org_id()) AND (i.status <> 'closed'::injury_status))))))
  with check ((org_id = auth_org_id()));
drop policy if exists nutrition_targets_coach_insert on public.nutrition_targets;
create policy nutrition_targets_coach_insert on public.nutrition_targets
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role]) AND (created_by = auth_user_id())));
drop policy if exists nutrition_targets_coach_update on public.nutrition_targets;
create policy nutrition_targets_coach_update on public.nutrition_targets
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])))
  with check ((org_id = auth_org_id()));
drop policy if exists nutrition_targets_medical_insert on public.nutrition_targets;
create policy nutrition_targets_medical_insert on public.nutrition_targets
  as permissive
  for insert
  to authenticated
  with check (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (created_by = auth_user_id()) AND (athlete_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM injuries i
  WHERE ((i.athlete_id = nutrition_targets.athlete_id) AND (i.org_id = auth_org_id()) AND (i.status <> 'closed'::injury_status))))));
drop policy if exists nutrition_targets_medical_update on public.nutrition_targets;
create policy nutrition_targets_medical_update on public.nutrition_targets
  as permissive
  for update
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['medical'::app_role]) AND (athlete_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM injuries i
  WHERE ((i.athlete_id = nutrition_targets.athlete_id) AND (i.org_id = auth_org_id()) AND (i.status <> 'closed'::injury_status))))))
  with check ((org_id = auth_org_id()));
drop policy if exists threshold_revisions_coach_select on public.threshold_revisions;
create policy threshold_revisions_coach_select on public.threshold_revisions
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])));
drop policy if exists thresholds_coach_select on public.thresholds;
create policy thresholds_coach_select on public.thresholds
  as permissive
  for select
  to authenticated
  using (((org_id = auth_org_id()) AND auth_has_any_role(ARRAY['coach'::app_role])));
-- 2. The GPS work: the grant and constraint 0064 and 0072 added.
revoke update on public.gps_records from authenticated;
alter table public.gps_records drop constraint if exists gps_records_one_per_athlete_session;

-- 3. Forget the ten migrations, so the CLI will re-offer them rather than
--    believing they are still applied.
delete from supabase_migrations.schema_migrations
 where version in ('0063','0064','0065','0066','0067','0068','0069','0070','0071','0072');

commit;

-- After running, expect:
--   app_role: athlete, coach, medical, admin, strength_conditioning, nutritionist
--   the last two inert, for the reason in the header.
